# 创建一个列表和一个数组

In [3]:
import numpy as np
LIST = [1,3,5,7]
ARR = np.array(LIST)

print(type(ARR)) # <class 'numpy.ndarray'>

print(ARR[0]) # 1

print(ARR[2:]) # [5 7]

<class 'numpy.ndarray'>
1
[5 7]


----
**列表与数组的区别:**
**首要区别：列表元素可以是任意类型的元素，数组元素必须是相同类型**

In [4]:
print(ARR.dtype) # int64

int64


----
**一旦创建了一个数组，那它的dtype也就固定了，它只能储存相同类型的元素，
这时候如果储存一个浮点数类型，系统会自动将其转化为浮点数类型**

In [5]:
ARR[-1] = 1.934
print(ARR) # [1 3 5 1]

[1 3 5 1]


# 数组的创建

In [6]:
a0 = np.zeros(5,dtype=float)
print(a0) # [0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0.]


In [7]:
a1 = np.ones(5,dtype=int)
print(a1) # [1 1 1 1 1]

[1 1 1 1 1]


In [8]:
a3 = np.empty(4) # 产生的值都是空值
a3.fill(5.5) # 填充值为5.5
print(a3) # [5.5 5.5 5.5 5.5]

[5.5 5.5 5.5 5.5]


---
**创建常用的随机数字的数组，np.random模块包含愈多可用于创建随机数组的函数。**
**下面是生成一个服从标准正态分布（均值为0方差为1）的5个随机数样本数组:**

In [9]:
a4 = np.random.randn(5)
print(a4)

[ 0.47882348  0.0284257   1.66867212  1.16974572 -1.00987525]


# 多维数组

---
**生成二维数组**

In [10]:
LIST2 = [[1,2],[3,4]]
ARR2 = np.array(LIST2)
print(ARR2)

[[1 2]
 [3 4]]


---
**分别返回列表和数组中的“2”**

**数组的索引更为自然**

In [18]:
print(LIST2[0][1])
print(ARR2[0,1])
print(ARR2[0,:]) # 获得第一行所有元素
print(ARR2[:,1]) # 获得第二列所有元素
print()

2
2
[1 2]
[2 4]


---
**返回2行3列的array，且值全部为0**

In [13]:
a5 = np.zeros((2,3),dtype=float)
print(a5)

[[0. 0. 0.]
 [0. 0. 0.]]


---
**返回2行4列的array，且值为均值为10，标准差为3的正态分布的随机数**

In [14]:
a6 = np.random.normal(10,3,(2,4))
print(a6)

[[16.10601005  8.17381585 11.06139679  4.64466494]
 [ 6.05995598  6.52111227  5.77300574  6.67457172]]


---
**实际上，只要元素的总数不变，数组的形状就可以随时改变。例如想要一个数字从0增加的2x4数组，最简单的方法如下：**

In [15]:
arr1 = np.arange(8)
print(arr1)

[0 1 2 3 4 5 6 7]


In [16]:
arr2 = np.arange(8).reshape(2,4)
print(arr2)

[[0 1 2 3]
 [4 5 6 7]]


In [19]:
arr1 = np.arange(8)
arr2 = arr1.reshape(2,4)
arr1[0] = 1000
print(arr1)
print(arr2)

[1000    1    2    3    4    5    6    7]
[[1000    1    2    3]
 [   4    5    6    7]]


In [20]:
arr3 = arr1.copy()
arr1[0] = 1
print(arr3)
print(arr1)
print(arr2)

[1000    1    2    3    4    5    6    7]
[1 1 2 3 4 5 6 7]
[[1 1 2 3]
 [4 5 6 7]]


# 多维数组的索引和切片
---
**使用多维数组，仍然可以像一维数组一样使用切片，并且多维数组可以在不同维度中混合匹配切片和单个索引**

In [22]:
print(arr2)
print(arr2[1,2:3])

[[1 1 2 3]
 [4 5 6 7]]
[6]


In [23]:
print(arr2[:,2])

[2 6]


In [24]:
print(arr2[1][2:3])

[6]


In [26]:
LIST = [[1,2,3],[4,5,6]]
print([i[2] for i in LIST])

[3, 6]


In [27]:
print(arr2[0])
print(arr2[1])

[1 1 2 3]
[4 5 6 7]


In [28]:
arr = arr2
print('Data type               :',arr.dtype)
print('Total number of elements:',arr.size)
print('Number of dimensions    :',arr.ndim)
print('Shape (dimensionality)  :',arr.shape)
print('Memory used (in bytes)  :',arr.dtype)

Data type               : int64
Total number of elements: 8
Number of dimensions    : 2
Shape (dimensionality)  : (2, 4)
Memory used (in bytes)  : int64


In [30]:
print('Minmum and maximum             :',arr.min(),arr.max())
print('Sum and product of all elements:',arr.sum(),arr.prod())
print('Mean and standard deviation    :',arr.mean(),arr.std())

Minmum and maximum             : 1 7
Sum and product of all elements: 29 5040
Mean and standard deviation    : 3.625 2.117634293262177


In [36]:
print('The sum of elements along the rows is  :',arr.sum(axis=1))
print('The sum of elements along the columns is  :',arr.sum(axis=0))
print(arr)
print(arr.cumsum(axis=1)) # 使数组沿着横轴计算
print(arr.cumsum(axis=0)) # 使数组沿着纵轴计算

The sum of elements along the rows is  : [ 7 22]
The sum of elements along the columns is  : [ 5  6  8 10]
[[1 1 2 3]
 [4 5 6 7]]
[[ 1  2  4  7]
 [ 4  9 15 22]]
[[ 1  1  2  3]
 [ 5  6  8 10]]


# 数组的转置

In [37]:
print("Array: \n",arr)
print("Transpose: \n",arr.T)

Array: 
 [[1 1 2 3]
 [4 5 6 7]]
Transpose: 
 [[1 4]
 [1 5]
 [2 6]
 [3 7]]


# 数组的运算
---
**NumPy专为科学计算而生，数组支持所有常规的算术运算，NumPy库中包含
完整的基本数学函数，这些函数在数组的运算上也发发挥了很大的作用。一
般来说，数组的所有操作都是以元素对应的方式来实现的，即同时应用于数
组的所有元素，且一一对应**

In [39]:
arr1 = np.arange(4)
arr2 = np.arange(10,14)
print(arr1,'+',arr2,'=',arr1+arr2)

[0 1 2 3] + [10 11 12 13] = [10 12 14 16]


---
**值得注意的是，即使是乘法运算也是默认元素对应的方式，这与线性代
数的矩阵乘法不同，如下所示**

In [40]:
print(arr1,'*',arr2,'=',arr1*arr2)

[0 1 2 3] * [10 11 12 13] = [ 0 11 24 39]


In [41]:
print(1.5*arr1)

[0.  1.5 3.  4.5]


---
**NumPy提供了完整的数学函数，并且可以在整个数组上运行，其中包括
对数、指数、三角函数和双曲三角函数等。此外，SciPy还在scipy.special
模块中提供了一个丰富的特殊函数库，具有贝塞尔、艾里、菲涅耳等古典特殊
功能。例如在0到2π之间的正弦函数上采集20个点，实现方式就像下面代码
所展示的这样简单。**

In [48]:
x = np.linspace(0,2*np.pi,20)
y = np.sin(x)
print(y)

[ 0.00000000e+00  3.24699469e-01  6.14212713e-01  8.37166478e-01
  9.69400266e-01  9.96584493e-01  9.15773327e-01  7.35723911e-01
  4.75947393e-01  1.64594590e-01 -1.64594590e-01 -4.75947393e-01
 -7.35723911e-01 -9.15773327e-01 -9.96584493e-01 -9.69400266e-01
 -8.37166478e-01 -6.14212713e-01 -3.24699469e-01 -2.44929360e-16]


In [3]:
from emoji import emojize
print(emojize(":thumbs_up:"))

ModuleNotFoundError: No module named 'emoji'

In [1]:
def array_test():
    ar = [3, 2, 4, 5]

    ar.pop()

    ar.append(6)

    print(ar)
    print("Index of 4: ", ar.index(4))  # index of given value

    ar.remove(4)  # remove the first occurence of item with given value
    print("Removed 4: ", ar)

    ar.reverse()
    print("reversed: ", ar)
    print("sorted return: ", sorted(ar))

    ar.sort()
    print("sorted in place: ", ar)


def main():
    array_test()


if __name__ == "__main__":
    main()

[3, 2, 4, 6]
Index of 4:  2
Removed 4:  [3, 2, 6]
reversed:  [6, 2, 3]
sorted return:  [2, 3, 6]
sorted in place:  [2, 3, 6]
